version: 2.1

executors:
  golang:
    working_directory: /go/src/github.com/mercari/terraform-provider-spinnaker
    docker:
      - image:  golang:1.14
        environment:
          GO111MODULE: "on"

jobs:
  test:
    executor: golang
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  release:
    executor: golang
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  main:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
