version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/mercari/terraform-provider-spinnaker
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build 

  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/mercari/terraform-provider-spinnaker
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  release:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  test-and-release:
    jobs:
      - build
      - test
      - release:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
